name: movies_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  flutter_screenutil: ^5.9.1
  google_fonts: ^6.3.1
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.5
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_Bold.ttf
        - asset: assets/fonts/Inter_Medium.ttf
        - asset: assets/fonts/Inter_Regular.ttf
        - asset: assets/fonts/Inter_SemiBold.ttf
